set(MODULE Http)
set(PACKAGE Ndmspc${MODULE})
file(GLOB SRCS RELATIVE "${CMAKE_CURRENT_SOURCE_DIR}" "*.cxx")

set(MY_INCLUDE_DIRS
  ${NLOHMANN_JSON_INCLUDE_DIRS}
  ${HTTPLIB_INCLUDE_DIRS}
  ${JWT_CPP_INCLUDE_DIRS}
  ${OpenSSL_INCLUDE_DIRS}
  ${CMAKE_SOURCE_DIR}/core/cli
)
include_directories(${MY_INCLUDE_DIRS})
set(MY_EXTERNAL_LIBS
  ${NLOHMANN_JSON_LIBRARIES}
  ${OpenSSL_LIBRARIES}
  RHTTP
  NdmspcCore
)

RootLib(${PACKAGE} "${SRCS}" "${MY_EXTERNAL_LIBS}" "")
target_compile_definitions(${PACKAGE} PRIVATE CPPHTTPLIB_OPENSSL_SUPPORT)

add_subdirectory(cli)
