#!/bin/bash
NDMSPC_INIT_DIR=${NDMSPC_INIT_DIR-/var/tmp/ndmspc-init}
PROJECT_DIR="$(dirname $(dirname $(readlink -m $0)))"
cd ${NDMSPC_INIT_DIR}/eos-ansible
mkdir -p /data/00 /data/01

cat >vars.yml <<EOF
eos_css_scripts:
  - cat.sh
  - sort.sh
  - info.sh
  - ndmspc.sh
EOF

ansible-playbook -i inventory/eos-local playbooks/eos.yml --tags install -e eos_css_script_directory=${NDMSPC_INIT_DIR}/ci/eos/css_plugin/scripts -e @vars.yml
