#!/bin/bash

PROJECT_DIR="$(dirname $(dirname $(readlink -m $0)))"
cd /ndmspc/eos-ansible
mkdir -p /data/00 /data/01

cat >vars.yml <<EOF
eos_css_scripts:
  - cat.sh
  - sort.sh
  - info.sh
  - ndmspc.sh
EOF

ansible-playbook -i inventory/eos-local playbooks/eos.yml --tags install -e eos_css_script_directory=/ndmspc/ci/eos/css_plugin/scripts -e @vars.yml

