#!/bin/bash
NDMSPC_LOG_XRD=${NDMSPC_LOG_XRD-""}
NDMSPC_LOGDIR_XRD=${NDMSPC_LOGDIR_XRD-"root://eos.ndmspc.io//eos/ndmspc/scratch/ndmspc/logs"}
NDMSPC_LOGFILE_XRD=${NDMSPC_LOGFILE_XRD-"ndmspc.log"}
NDMSPC_LOG_TYPE=${NDMSPC_LOG_TYPE-"error-only"}
NDMSPC_MACRO_SRC=
NDMSPC_MACRO_FILENAME=${NDMSPC_MACRO_FILENAME-"NdmspcMacro.C"}
NDMCPS_SANDBOX_BASE_DIR=${NDMCPS_SANDBOX_BASE_DIR-"/tmp/ndmspc"}
NDMCPS_SANDBOX_CLEANUP=${NDMCPS_SANDBOX_CLEANUP-1}
NDMSPC_MACRO_DIR=${NDMSPC_MACRO_DIR-"/usr/share/ndmspc/macros"}

function help() {
  echo "$0 <cmd> <arg1> <arg2> ... <argN>"
  echo "$0 _run '\"test_single.json\"'"
}

if [ -z "$1" ];then
  help
  exit 1
fi

# NDMSPC_LOGDIR_XRD="root://eos.ndmspc.io//eos/ndmspc/scratch/ndmspc/logs"
# NDMSPC_LOG_TYPE="always"
if [ -z "$NDMSPC_LOG_XRD" ] ;then
  if [ -n "$NDMSPC_LOGDIR_XRD" ];then
    [ -n "$NDMSPC_LOGDIR_XRD" ] &&  NDMSPC_LOG_XRD="$NDMSPC_LOGDIR_XRD"
    [ -n "$SALSA_CLUSTER_ID" ] && NDMSPC_LOG_XRD="$NDMSPC_LOGDIR_XRD/$SALSA_CLUSTER_ID"
    [ -n "$SALSA_JOB_ID" ] && NDMSPC_LOG_XRD="$NDMSPC_LOG_XRD/$SALSA_JOB_ID"
    [ -n "$SALSA_TASK_ID" ] && NDMSPC_LOG_XRD="$NDMSPC_LOG_XRD/$SALSA_TASK_ID"
    [ -n "$NDMSPC_LOG_XRD" ] && NDMSPC_LOG_XRD="$NDMSPC_LOG_XRD/$NDMSPC_LOGFILE_XRD"
  fi
fi

# the directory of the script
# DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
# DIR=/tmp/ndmspc
NDMCPS_SANDBOX_BASE_DIR="$NDMCPS_SANDBOX_BASE_DIR/$(id -u)"

[ -d $NDMCPS_SANDBOX_BASE_DIR ] || mkdir -p $NDMCPS_SANDBOX_BASE_DIR

export HOME={HOME-$NDMCPS_SANDBOX_BASE_DIR}

# the temp directory used, within $DIR
# omit the -p parameter to create a temporal directory in the default location
WORK_DIR=`mktemp -d -p "$NDMCPS_SANDBOX_BASE_DIR"`
LOG_FILE="$WORK_DIR/ndmspc.log"

echo "NDMSPC_LOG_XRD=$NDMSPC_LOG_XRD" 2>&1 | tee -a $LOG_FILE
# echo "NDMSPC_LOGDIR_XRD=$NDMSPC_LOGDIR_XRD"
# echo "NDMSPC_LOGFILE_XRD=$NDMSPC_LOGFILE_XRD"
echo "NDMSPC_LOG_TYPE=$NDMSPC_LOG_TYPE" 2>&1 | tee -a $LOG_FILE

MY_PWD=$(pwd)
cd $WORK_DIR

MY_CMD=$@
if [[ $1 == "_run" ]];then
  shift
  MY_CMD="root -b -q $NDMSPC_MACRO_DIR/NdmspcRun.C"
  [ -n "$1" ] && MY_CMD="${MY_CMD}'($(echo $1 | tr -d \'))'"
  shift

  # ndmspc _run '"config.json"' "<next lines (multiple space separated)>"
  # "base64|$(cat RsnBin.C | base64 -w 0)|NdmspcMacro.C" 
  # "https://gitlab.science.upjs.sk/jf/students/phd/2023/veronika-barbasova/myo2/-/raw/main/macros/RsnFunctions.h|RsnFunctions.h" 
  # "local|$(pwd)/test_single.json|config.json"
  # "root://eos.ndmspc.io//eos/ndmspc/scratch/test/test_single.json|config.json"
  # "dir|cp|$(pwd)/*"
  # "dir|xrdcp|root://eos.ndmspc.io//eos/ndmspc/scratch/test/mvala/test/xxx"
  MY_EXTRA=$(echo $* | tr -d \'\")
  for arg in $(echo $MY_EXTRA);do
    # echo $arg
    if [[ $arg == local* ]];then
      content=$(echo "$arg" | cut -d '|' -f2)
      filename=$(echo "$arg" |cut -d '|' -f3)
      cp -f $content $WORK_DIR/$filename 2>&1 | tee -a $LOG_FILE
      echo "Filename created : $WORK_DIR/$filename" 2>&1 | tee -a $LOG_FILE
    elif [[ $arg == dir* ]];then
      type=$(echo "$arg" | cut -d '|' -f2)
      dir=$(echo "$arg" |cut -d '|' -f3)
      if [[ $type == cp* ]];then
        echo "Doing 'cp -a $dir $WORK_DIR/'" 2>&1 | tee -a $LOG_FILE
        cp -a $dir $WORK_DIR/ 2>&1 | tee -a $LOG_FILE
      elif [[ $type == xrdcp* ]];then
        echo "Doing 'xrdcp -r $dir $WORK_DIR/'" 2>&1 | tee -a $LOG_FILE
        xrdcp -r $dir $WORK_DIR/ 2>&1 | tee -a $LOG_FILE
        mv $WORK_DIR/$(basename $dir)/* . 2>&1 | tee -a $LOG_FILE
        rm -rf $WORK_DIR/$(basename $dir) 2>&1 | tee -a $LOG_FILE
      fi
      
    elif [[ $arg == base64* ]];then
      content=$(echo "$arg" | cut -d '|' -f2)
      filename=$(echo "$arg" |cut -d '|' -f3)
      echo $content | base64 -d > $WORK_DIR/$filename 
      echo "Filename created : $WORK_DIR/$filename" 2>&1 | tee -a $LOG_FILE
    elif [[ $arg == root* ]];then
      content=$(echo "$arg" | cut -d '|' -f1)
      filename=$(echo "$arg" |cut -d '|' -f2)
      xrdcp $content - > $WORK_DIR/$filename
      echo "Filename created : $WORK_DIR/$filename" 2>&1 | tee -a $LOG_FILE
    elif [[ $arg == http* ]] || [[ $arg == https* ]];then
      content=$(echo "$arg" | cut -d '|' -f1)
      filename=$(echo "$arg" |cut -d '|' -f2)
      curl -s $content -L > $WORK_DIR/$filename
      echo "Filename created : $WORK_DIR/$filename" 2>&1 | tee -a $LOG_FILE
      
    fi
  done
  export ROOT_INCLUDE_PATH=".:$ROOT_INCLUDE_PATH"
cat <<EOF > $WORK_DIR/rootlogon.C
void rootlogon() {
  gROOT->ProcessLine(".include .");
}
EOF

cat <<EOF > $WORK_DIR/rootlogoff.C
void rootlogoff() {
  gROOT->GetListOfCanvases()->Clear();
}
EOF
fi
echo "Working directory : $(pwd)" 2>&1 | tee -a $LOG_FILE
ls -al 2>&1 | tee -a $LOG_FILE

# check if tmp dir was created
if [[ ! "$WORK_DIR" || ! -d "$WORK_DIR" ]]; then
  echo "Could not create temp dir" 2>&1 | tee -a $LOG_FILE
  exit 1
fi

if [ -n "$NDMSPC_LOG_XRD" ];then
  if ! command -v xrdcp &> /dev/null; then
      echo "Warning: 'xrdcp' is not installed !!! Please install it first (dnf install xrootd-client) to send logs to '$NDMSPC_LOG_XRD' ..." 2>&1 | tee -a $LOG_FILE
      export NDMSPC_LOG_XRD=""
  fi
fi

# deletes the temp directory
function cleanup {
  cd $MY_PWD
  # cat $LOG_FILE
  if [[ $NDMCPS_SANDBOX_CLEANUP == 1 ]];then
    rm -rf "$WORK_DIR"
    echo "Deleted temp working directory '$WORK_DIR'."
  else
    echo "Temp working directory '$WORK_DIR' was NOT deleted."
  fi
}

function +() (
  set -f  # no double expand
  eval "$MY_CMD" 2>&1 | tee -a $LOG_FILE
  RC=${PIPESTATUS[0]}
  echo "cmd='$MY_CMD' rc=$RC" | tee -a $LOG_FILE
  # $@ | tee >> $LOG_FILE
  if [ -n "$NDMSPC_LOG_XRD" ];then
    
    case $NDMSPC_LOG_TYPE in
      error-only)
        [[ $RC -gt 0 ]] && export NDMSPC_LOG_COPY=1
        ;;
      always)
        export NDMSPC_LOG_COPY=1
        ;;
      *)
        export NDMSPC_LOG_COPY=0
        ;;
    esac
    if [[ $NDMSPC_LOG_COPY == 1 ]];then
      echo "Copying logs (type=$NDMSPC_LOG_TYPE) to '$NDMSPC_LOG_XRD' ..."
      NDMSPC_LOGFILE_HTTP=$(echo ${NDMSPC_LOG_XRD/root:\/\//} | tr -s /)
      NDMSPC_LOGFILE_HTTP="https://$NDMSPC_LOGFILE_HTTP"
      xrdcp -f $LOG_FILE $NDMSPC_LOG_XRD && echo -e "Logs:\n\tcurl -L $NDMSPC_LOGFILE_HTTP\n\txrdcp -f $NDMSPC_LOG_XRD /tmp/ndmspc.log\n" 2>&1 | tee -a $LOG_FILE || { echo "Warning: Problem doing 'xrdcp -f "$LOG_FILE" "$NDMSPC_LOG_XRD" !!! Log is not produced at $NDMSPC_LOG_XRD ..." 2>&1 | tee -a $LOG_FILE; true; }
    fi
    
  fi

  return $RC # real rc
)  

# register the cleanup function to be called on the EXIT signal
trap cleanup EXIT INT

echo "Running '$MY_CMD' ..." 2>&1 | tee -a $LOG_FILE
+ $MY_CMD

exit $RC