#!/bin/bash
PROJECT_DIR="$(dirname $(dirname $(readlink -m $0)))"


echo $PROJECT_DIR

ansible-galaxy install -r $PROJECT_DIR/etc/slurm/requirements.yml
dd if=/dev/urandom bs=1 count=1024 >/etc/munge/munge.key
chown munge:munge /etc/munge/munge.key
chmod 400 /etc/munge/munge.key

ansible-playbook -i localhost, -e ansible_connection=local $PROJECT_DIR/etc/slurm/slurm.yaml
