# FindLIBWEBSOCKETS.cmake
#
# This module defines
# LIBWEBSOCKETS_FOUND, whether LIBWEBSOCKETS was found
# LIBWEBSOCKETS_INCLUDE_DIRS, include directories
# LIBWEBSOCKETS_LIBRARIES, link libraries

find_path(LIBWEBSOCKETS_INCLUDE_DIRS
  NAMES libwebsockets.h
  PATHS ${LIBWEBSOCKET_ROOT}/include /usr/local/include /usr/include
)

find_library(LIBWEBSOCKETS_LIBRARIES
  NAMES websockets
  PATHS ${LIBWEBSOCKET_ROOT}/lib /usr/local/lib /usr/lib
)

include(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(LIBWEBSOCKETS DEFAULT_MSG LIBWEBSOCKETS_LIBRARIES LIBWEBSOCKETS_INCLUDE_DIRS)

mark_as_advanced(LIBWEBSOCKETS_INCLUDE_DIRS LIBWEBSOCKETS_LIBRARIES)
