find_package(NLOHMANN_JSON REQUIRED)
if(PROTOBUF_ROOT)
  find_package(Protobuf CONFIG REQUIRED)
  set(Protobuf_LIBRARIES "${PROTOBUF_ROOT}/lib")
  set(Protobuf_INCLUDE_DIR "${PROTOBUF_ROOT}/include")
endif()
find_package(CURL REQUIRED)
find_package(OpenSSL REQUIRED)
find_package(LIBUV REQUIRED)
find_package(LIBWEBSOCKETS REQUIRED)

if(WITH_OPENTELEMETRY)
  # TODO: Remove it: Temporary fix for opentelemetry-cpp
  add_definitions(-Wno-cpp)
  message(STATUS "Compiling with OpenTelemetry support")
  find_package(opentelemetry-cpp CONFIG REQUIRED)
  message(STATUS "Found opentelemetry-cpp: ${opentelemetry-cpp_VERSION}")
endif()


if(WITH_PARQUET)
  message(STATUS "Compiling with Parquet support")
  set(ARROW_WITH_PARQUET ON)
  find_package(Arrow REQUIRED)
  find_package(Parquet REQUIRED)
else()
  message(STATUS "Compiling without Parquet support")
  # set(ARROW_WITH_PARQUET OFF)
endif()

find_package(Root REQUIRED)
include(ROOTMacros)
