find_package(NLOHMANN_JSON REQUIRED)
if(PROTOBUF_ROOT)
  find_package(Protobuf CONFIG REQUIRED)
  set(Protobuf_LIBRARIES "${PROTOBUF_ROOT}/lib")
  set(Protobuf_INCLUDE_DIR "${PROTOBUF_ROOT}/include")
endif()
find_package(CURL REQUIRED)
find_package(OpenSSL REQUIRED)
find_package(LIBUV REQUIRED)
find_package(LIBWEBSOCKETS REQUIRED)

# if(WITH_OPENTELEMETRY)
#   # TODO: Remove it: Temporary fix for opentelemetry-cpp
#   add_definitions(-Wno-cpp)
#   message(STATUS "Compiling with OpenTelemetry support")
#   find_package(opentelemetry-cpp CONFIG REQUIRED)
#   message(STATUS "Found opentelemetry-cpp: ${opentelemetry-cpp_VERSION}")
# endif()


if(WITH_PARQUET)
  message(STATUS "Compiling with Parquet support")
  set(ARROW_WITH_PARQUET ON)
  find_package(Arrow REQUIRED)
  find_package(Parquet REQUIRED)
else()
  message(STATUS "Compiling without Parquet support")
  # set(ARROW_WITH_PARQUET OFF)
endif()
if(WITH_NUMCAL)
  message(STATUS "Compiling with Numcal support")
  find_package(GINAC REQUIRED)
  find_package(CUBA REQUIRED)
endif()

message(STATUS "Compiling with ZeroMQ IPC support")
find_package(PkgConfig QUIET)
if(PkgConfig_FOUND)
  pkg_check_modules(ZEROMQ QUIET libzmq)
endif()

if(NOT ZEROMQ_FOUND)
  find_path(ZEROMQ_INCLUDE_DIRS zmq.h)
  find_library(ZEROMQ_LIBRARIES NAMES zmq)
  if(NOT ZEROMQ_INCLUDE_DIRS OR NOT ZEROMQ_LIBRARIES)
    message(FATAL_ERROR "ZeroMQ development files are required (zmq.h and libzmq).")
  endif()
endif()

find_package(Root REQUIRED)
include(ROOTMacros)
